displayName: namo-training
jobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-4
      replicaCount: 1
      containerSpec:
        imageUri: 'asia-southeast1-docker.pkg.dev/namo-legacy-identity/namo-nexus/web'
        command: []
        args: []